import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { substrates, categories, details, detailSteps, warningConditions, failureCases, detailFailureLinks } from './schema';

// Load environment variables for standalone script execution
import { config } from 'dotenv';
config({ path: '.env.local' });

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

async function seed() {
  console.log('🌱 Seeding database...\n');

  // Clear existing data
  console.log('🗑️  Clearing existing data...');
  await db.delete(detailFailureLinks);
  await db.delete(detailSteps);
  await db.delete(warningConditions);
  await db.delete(failureCases);
  await db.delete(details);
  await db.delete(categories);
  await db.delete(substrates);
  console.log('✅ Existing data cleared\n');

  // Seed Substrates
  console.log('📦 Seeding substrates...');
  const substrateData = [
    { id: 'long-run-metal', name: 'Long-Run Metal', description: 'Corrugated, trapezoidal, and standing seam metal roofing systems', iconUrl: '/icons/substrates/metal.svg', sortOrder: 1 },
    { id: 'membrane', name: 'Membrane', description: 'TPO, PVC, EPDM, and other membrane roofing applications', iconUrl: '/icons/substrates/membrane.svg', sortOrder: 2 },
    { id: 'asphalt-shingle', name: 'Asphalt Shingle', description: 'Asphalt shingle installation and detailing', iconUrl: '/icons/substrates/shingle.svg', sortOrder: 3 },
    { id: 'concrete-tile', name: 'Concrete Tile', description: 'Concrete tile roofing systems and accessories', iconUrl: '/icons/substrates/concrete.svg', sortOrder: 4 },
    { id: 'clay-tile', name: 'Clay Tile', description: 'Traditional and modern clay tile installations', iconUrl: '/icons/substrates/clay.svg', sortOrder: 5 },
    { id: 'pressed-metal-tile', name: 'Pressed Metal Tile', description: 'Pressed metal tile systems including shake profiles', iconUrl: '/icons/substrates/pressed.svg', sortOrder: 6 },
  ];
  await db.insert(substrates).values(substrateData);
  console.log(`✅ Seeded ${substrateData.length} substrates\n`);

  // Seed Categories
  console.log('📁 Seeding categories...');
  const categoryData = [
    // Long-Run Metal
    { id: 'lrm-flashings', substrateId: 'long-run-metal', name: 'Flashings', description: 'Wall, barge, apron, and step flashings', iconUrl: '/icons/categories/flashings.svg', sortOrder: 1 },
    { id: 'lrm-ridges', substrateId: 'long-run-metal', name: 'Ridges & Hips', description: 'Ridge capping and hip details', iconUrl: '/icons/categories/ridges.svg', sortOrder: 2 },
    { id: 'lrm-valleys', substrateId: 'long-run-metal', name: 'Valleys', description: 'Valley gutter and intersection details', iconUrl: '/icons/categories/valleys.svg', sortOrder: 3 },
    { id: 'lrm-penetrations', substrateId: 'long-run-metal', name: 'Penetrations', description: 'Pipe, vent, and skylight penetrations', iconUrl: '/icons/categories/penetrations.svg', sortOrder: 4 },
    { id: 'lrm-gutters', substrateId: 'long-run-metal', name: 'Gutters & Downpipes', description: 'Gutter connections and accessories', iconUrl: '/icons/categories/gutters.svg', sortOrder: 5 },
    { id: 'lrm-ventilation', substrateId: 'long-run-metal', name: 'Ventilation', description: 'Roof space ventilation requirements', iconUrl: '/icons/categories/ventilation.svg', sortOrder: 6 },
    // Membrane
    { id: 'mem-flashings', substrateId: 'membrane', name: 'Flashings', description: 'Membrane terminations and upstands', iconUrl: '/icons/categories/flashings.svg', sortOrder: 1 },
    { id: 'mem-penetrations', substrateId: 'membrane', name: 'Penetrations', description: 'Membrane penetration boots and seals', iconUrl: '/icons/categories/penetrations.svg', sortOrder: 2 },
    { id: 'mem-drains', substrateId: 'membrane', name: 'Drains & Outlets', description: 'Internal and external drainage', iconUrl: '/icons/categories/drainage.svg', sortOrder: 3 },
    { id: 'mem-edges', substrateId: 'membrane', name: 'Edges & Parapets', description: 'Edge trims and parapet details', iconUrl: '/icons/categories/edges.svg', sortOrder: 4 },
    // Asphalt Shingle
    { id: 'ash-starter', substrateId: 'asphalt-shingle', name: 'Starter & Eaves', description: 'Starter strips and eave details', iconUrl: '/icons/categories/eaves.svg', sortOrder: 1 },
    { id: 'ash-ridges', substrateId: 'asphalt-shingle', name: 'Ridges & Hips', description: 'Cap shingles and hip treatments', iconUrl: '/icons/categories/ridges.svg', sortOrder: 2 },
    { id: 'ash-valleys', substrateId: 'asphalt-shingle', name: 'Valleys', description: 'Open and closed valley methods', iconUrl: '/icons/categories/valleys.svg', sortOrder: 3 },
    { id: 'ash-flashings', substrateId: 'asphalt-shingle', name: 'Flashings', description: 'Step and counter flashings', iconUrl: '/icons/categories/flashings.svg', sortOrder: 4 },
    // Concrete Tile
    { id: 'ct-flashings', substrateId: 'concrete-tile', name: 'Flashings', description: 'Wall and penetration flashings', iconUrl: '/icons/categories/flashings.svg', sortOrder: 1 },
    { id: 'ct-ridges', substrateId: 'concrete-tile', name: 'Ridges & Hips', description: 'Ridge and hip tile installation', iconUrl: '/icons/categories/ridges.svg', sortOrder: 2 },
    { id: 'ct-valleys', substrateId: 'concrete-tile', name: 'Valleys', description: 'Valley tile arrangements', iconUrl: '/icons/categories/valleys.svg', sortOrder: 3 },
    { id: 'ct-ventilation', substrateId: 'concrete-tile', name: 'Ventilation', description: 'Tile ventilation products', iconUrl: '/icons/categories/ventilation.svg', sortOrder: 4 },
    // Clay Tile
    { id: 'clt-flashings', substrateId: 'clay-tile', name: 'Flashings', description: 'Traditional clay tile flashings', iconUrl: '/icons/categories/flashings.svg', sortOrder: 1 },
    { id: 'clt-ridges', substrateId: 'clay-tile', name: 'Ridges & Hips', description: 'Ridge and hip treatments', iconUrl: '/icons/categories/ridges.svg', sortOrder: 2 },
    { id: 'clt-valleys', substrateId: 'clay-tile', name: 'Valleys', description: 'Valley construction methods', iconUrl: '/icons/categories/valleys.svg', sortOrder: 3 },
    // Pressed Metal Tile
    { id: 'pmt-flashings', substrateId: 'pressed-metal-tile', name: 'Flashings', description: 'Pressed metal tile flashings', iconUrl: '/icons/categories/flashings.svg', sortOrder: 1 },
    { id: 'pmt-ridges', substrateId: 'pressed-metal-tile', name: 'Ridges & Hips', description: 'Ridge cap installation', iconUrl: '/icons/categories/ridges.svg', sortOrder: 2 },
    { id: 'pmt-valleys', substrateId: 'pressed-metal-tile', name: 'Valleys', description: 'Valley pan details', iconUrl: '/icons/categories/valleys.svg', sortOrder: 3 },
  ];
  await db.insert(categories).values(categoryData);
  console.log(`✅ Seeded ${categoryData.length} categories\n`);

  // Seed Details - RANZ Roofing Guide Details with 3D Models
  console.log('📋 Seeding details...');
  const detailData = [
    // ============================================
    // ROOFING FLASHINGS (F01-F16) - Long-Run Metal
    // ============================================
    {
      id: 'lrm-f01',
      code: 'F01',
      name: 'Drip Edge Flashing under 10°',
      description: 'Drip edge flashing detail for low-pitch profiled metal roofing under 10 degrees. Critical for water discharge at eaves.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf101.glb',
      minPitch: 3,
      maxPitch: 10,
      specifications: { material: 'Matching roof material', thickness: '0.55mm BMT', drip: '25mm minimum' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.5', title: 'Roof edge details' }],
      ventilationReqs: [{ check: 'Drip edge must not obstruct eave ventilation', required: true }],
    },
    {
      id: 'lrm-f02',
      code: 'F02',
      name: 'Change of Pitch Flashing',
      description: 'Flashing detail where roof pitch changes, such as mansard roofs or dormer intersections. Requires careful overlap detailing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf102.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { overlap: '200mm minimum onto lower pitch', upturn: '75mm onto steeper pitch', sealant: 'Butyl tape at overlap' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.5', title: 'Change of pitch details' }],
      ventilationReqs: [{ check: 'Ventilation path maintained at pitch change', required: true }],
    },
    {
      id: 'lrm-f03',
      code: 'F03',
      name: 'Barge Finish into Spouting',
      description: 'Barge (rake) flashing terminating into gutter/spouting. Provides weather protection at gable end while directing water into drainage.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf103.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { material: 'Matching roof material', cover: '100mm minimum', drip: 'Into gutter' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.5', title: 'Roof edge details' }],
      ventilationReqs: [{ check: 'Barge must not obstruct eave ventilation', required: true }],
    },
    {
      id: 'lrm-f04',
      code: 'F04',
      name: 'Hip Finish into Spouting',
      description: 'Hip capping termination into gutter/spouting. Critical junction requiring careful detailing for water management.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf104.glb',
      minPitch: 8,
      maxPitch: 45,
      specifications: { material: 'Matching hip capping', cover: 'Into gutter line', seal: 'Butyl tape at junction' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.7.3', title: 'Hip flashing requirements' }],
      ventilationReqs: [{ check: 'Hip does not block ventilation path from eave', required: true }],
    },
    {
      id: 'lrm-f05',
      code: 'F05',
      name: 'Hip, Apron, Barge Finish',
      description: 'Complex junction detail where hip capping meets apron flashing and barge board. Requires precise sequencing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf105.glb',
      minPitch: 8,
      maxPitch: 60,
      specifications: { sequence: 'Apron first, then hip, then barge', overlap: '150mm minimum at all junctions' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.7', title: 'Flashing requirements' }],
      ventilationReqs: [{ check: 'Maintain drainage path at all junctions', required: true }],
    },
    {
      id: 'lrm-f06',
      code: 'F06',
      name: 'Hip-Ridge Finish',
      description: 'Junction where hip capping meets ridge capping at roof apex. Critical weatherproofing point.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf106.glb',
      minPitch: 8,
      maxPitch: 45,
      specifications: { overlap: 'Hip under ridge', seal: 'Foam or butyl at junction', fixings: 'Through pans only' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.4', title: 'Ridge and hip details' }],
      ventilationReqs: [{ check: 'Consider ventilated ridge if roof space ventilation required', required: false }],
    },
    {
      id: 'lrm-f07',
      code: 'F07',
      name: 'Ridge to Gable End',
      description: 'Ridge capping termination at gable end. Ensures weather seal at exposed end of ridge.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf107.glb',
      minPitch: 8,
      maxPitch: 45,
      specifications: { closure: 'Formed end cap or folded', seal: 'Silicone at end', fixings: 'Type 17 screws' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.4', title: 'Ridge and hip details' }],
      ventilationReqs: [{ check: 'End cap must not block ridge ventilation if vented system', required: true }],
    },
    {
      id: 'lrm-f08',
      code: 'F08',
      name: 'Hip onto Barge',
      description: 'Hip capping landing onto barge flashing. Transition detail for hip-to-gable junction.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf108.glb',
      minPitch: 8,
      maxPitch: 45,
      specifications: { overlap: 'Hip over barge 100mm minimum', seal: 'Butyl tape', sequence: 'Barge first, then hip' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.7.3', title: 'Hip flashing requirements' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-f09',
      code: 'F09',
      name: 'Apron to Side Apron',
      description: 'Junction between front apron flashing and side apron flashing at roof-to-wall junction.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf209.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { overlap: '100mm minimum', upturn: '75mm both flashings', corner: 'Welded or folded' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.7.3', title: 'Apron flashing requirements' }],
      ventilationReqs: [{ check: 'Allow for drainage path at flashing base', required: true }],
    },
    {
      id: 'lrm-f10',
      code: 'F10',
      name: 'Valley Join & Ridge Finish',
      description: 'Complex junction where valley meets ridge. Requires careful sequencing and sealing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf210.glb',
      minPitch: 8,
      maxPitch: 60,
      specifications: { sequence: 'Valley under ridge', seal: 'Multiple layers required', width: 'Valley minimum 400mm at junction' },
      standardsRefs: [{ code: 'E2/AS1', clause: 'Table 20', title: 'Valley gutter dimensions' }],
      ventilationReqs: [{ check: 'Valley does not obstruct cross-ventilation path', required: true }],
    },
    {
      id: 'lrm-f11',
      code: 'F11',
      name: 'Valley onto Roof',
      description: 'Valley gutter termination onto lower roof section. Critical detail for water discharge.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf211.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { extension: 'Valley extends 150mm onto lower roof', seal: 'Butyl tape under', clearance: '100mm minimum from valley centre' },
      standardsRefs: [{ code: 'E2/AS1', clause: 'Table 20', title: 'Valley gutter dimensions' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-f12',
      code: 'F12',
      name: 'Side Apron, Barge Change of Pitch',
      description: 'Complex junction where side apron meets barge at a change of pitch. Multi-element flashing detail.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf212.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { sequence: 'Apron first, then pitch change, then barge', overlap: '150mm minimum at transitions' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.5', title: 'Change of pitch details' }],
      ventilationReqs: [{ check: 'Ventilation path maintained at pitch change', required: true }],
    },
    {
      id: 'lrm-f13',
      code: 'F13',
      name: 'Barge, Change of Pitch, Barge',
      description: 'Barge flashing through a change of pitch back to barge. Dormer or mansard detail.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf213.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { continuity: 'Barge continuous through pitch change', overlap: '200mm at pitch change' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.5', title: 'Change of pitch details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-f14',
      code: 'F14',
      name: 'Barge, Change of Pitch, Spouting',
      description: 'Barge flashing through change of pitch terminating into gutter. Combined detail.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-flashings',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf214.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { sequence: 'Upper barge, pitch transition, into gutter', overlap: '200mm at pitch change' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.5', title: 'Change of pitch details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-f15',
      code: 'F15',
      name: '100-300mm Diameter Penetration',
      description: 'Medium-sized penetration detail for pipes and ducts between 100mm and 300mm diameter.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf215.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { flashing: 'Fabricated metal or proprietary', upturn: '100mm minimum', apron: 'Required on high side' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [{ check: 'Penetration does not compromise air barrier', required: true }],
    },
    {
      id: 'lrm-f16',
      code: 'F16',
      name: '0-100mm Penetration through a Lap',
      description: 'Small penetration through a sheet lap. Requires careful sealing at lap junction.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/grf216.glb',
      minPitch: 3,
      maxPitch: 90,
      specifications: { boot: 'EPDM or silicone', seal: 'Additional sealant at lap', position: 'Centre of lap if possible' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    // ============================================
    // PENETRATIONS - CORRUGATED (C01-C11)
    // ============================================
    {
      id: 'lrm-c02',
      code: 'C02',
      name: 'Round Penetration - Overflashing (Corrugated)',
      description: 'Round pipe penetration through corrugated roofing using overflashing method. Suitable for larger pipes.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc102.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { flashing: 'Formed metal overflashing', overlap: '150mm upslope', seal: 'Butyl tape under' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [{ check: 'Hot flue requires clearance and heat shield', required: false }],
    },
    {
      id: 'lrm-c03',
      code: 'C03',
      name: 'Round Penetration - Undersoaker Level (Corrugated)',
      description: 'Round pipe penetration using undersoaker method on level section of corrugated roof.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc103.glb',
      minPitch: 0,
      maxPitch: 10,
      specifications: { soaker: 'Under roofing sheets', seal: 'Continuous around pipe', fixings: 'Through soaker into structure' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c04',
      code: 'C04',
      name: 'Round Penetration - Undersoaker with Arrowhead (Corrugated)',
      description: 'Round pipe penetration with undersoaker and arrowhead water diverter on corrugated roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc104.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { arrowhead: 'Min 200mm upslope', soaker: 'Full width of corrugation', seal: 'At pipe and edges' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c05',
      code: 'C05',
      name: 'Rectangular Penetration - Overflashing Level (Corrugated)',
      description: 'Rectangular penetration through corrugated roofing using overflashing on level/low pitch section.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc205.glb',
      minPitch: 0,
      maxPitch: 10,
      specifications: { flashing: 'Four-piece set', upturn: '75mm all sides', apron: 'Overlapping sequence' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c06',
      code: 'C06',
      name: 'Rectangular Penetration - Overflashing with Arrowhead (Corrugated)',
      description: 'Rectangular penetration with overflashing and arrowhead water diverter on corrugated roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc206.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { arrowhead: 'Full width of penetration plus 100mm each side', upturn: '100mm minimum' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c07',
      code: 'C07',
      name: 'Rectangular Penetration - Overflashing with Cricket (Corrugated)',
      description: 'Large rectangular penetration with cricket (saddle) diverter on corrugated roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc207.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { cricket: 'Required when width >750mm', height: 'Match penetration height', flashing: 'Integrated with cricket' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [{ check: 'Cricket must maintain positive drainage', required: true }],
    },
    {
      id: 'lrm-c08',
      code: 'C08',
      name: 'Rectangular Penetration - Undersoaker Level (Corrugated)',
      description: 'Rectangular penetration using undersoaker method on level corrugated roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc208.glb',
      minPitch: 0,
      maxPitch: 10,
      specifications: { soaker: 'Under roofing all sides', upturn: '75mm minimum', seal: 'Continuous perimeter' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c09',
      code: 'C09',
      name: 'Rectangular Penetration - Undersoaker with Arrowhead (Corrugated)',
      description: 'Rectangular penetration with undersoaker and arrowhead on corrugated roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc209.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { arrowhead: 'Under roofing upslope', soaker: 'Full perimeter', sequence: 'Soaker, arrowhead, roofing' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c10',
      code: 'C10',
      name: 'Rectangular Penetration - Undersoaker with Cricket (Corrugated)',
      description: 'Large rectangular penetration with undersoaker and cricket on corrugated roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc210.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { cricket: 'Under roofing with soaker', width: 'Match penetration plus 200mm', drainage: 'Both sides of cricket' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-c11',
      code: 'C11',
      name: 'Rectangular Penetration - Hidden Gutter (Corrugated)',
      description: 'Rectangular penetration using hidden gutter method on corrugated roofing for large penetrations.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpc211.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { gutter: 'Concealed behind penetration', width: '150mm minimum', fall: 'To sides' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [{ check: 'Hidden gutter overflow provision required', required: true }],
    },
    // ============================================
    // PENETRATIONS - RIB (R01-R11)
    // ============================================
    {
      id: 'lrm-r01',
      code: 'R01',
      name: 'Round Penetration - Directly Fixed Through Lap (Rib)',
      description: 'Round pipe penetration directly fixed through sheet lap on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr101.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { boot: 'EPDM or silicone', position: 'Through lap if possible', seal: 'Additional at lap junction' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r02',
      code: 'R02',
      name: 'Round Penetration - Overflashing (Rib)',
      description: 'Round pipe penetration through rib profile roofing using overflashing method.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr102.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { flashing: 'Formed to rib profile', overlap: '150mm upslope', seal: 'At rib peaks' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r03',
      code: 'R03',
      name: 'Round Penetration - Undersoaker Level (Rib)',
      description: 'Round pipe penetration using undersoaker on level section of rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr103.glb',
      minPitch: 0,
      maxPitch: 10,
      specifications: { soaker: 'Flat under ribs', seal: 'Foam at rib contact', fixings: 'Through pans' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r04',
      code: 'R04',
      name: 'Round Penetration - Undersoaker with Arrowhead (Rib)',
      description: 'Round pipe penetration with undersoaker and arrowhead on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr104.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { arrowhead: 'Formed to rib profile', soaker: 'Under ribs', integration: 'Welded or folded' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r05',
      code: 'R05',
      name: 'Rectangular Penetration - Overflashing Level (Rib)',
      description: 'Rectangular penetration using overflashing on level rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr205.glb',
      minPitch: 0,
      maxPitch: 10,
      specifications: { flashing: 'Profiled to match ribs', overlap: 'One full rib each side', upturn: '75mm minimum' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r06',
      code: 'R06',
      name: 'Rectangular Penetration - Overflashing with Arrowhead (Rib)',
      description: 'Rectangular penetration with overflashing and arrowhead on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr206.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { arrowhead: 'Profiled to ribs', extension: '200mm upslope', flashing: 'Integrated system' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r07',
      code: 'R07',
      name: 'Rectangular Penetration - Overflashing with Cricket (Rib)',
      description: 'Large rectangular penetration with cricket on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr207.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { cricket: 'Profiled to match roofing', width: 'Penetration width plus 200mm', drainage: 'To both sides' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [{ check: 'Cricket drainage must be clear', required: true }],
    },
    {
      id: 'lrm-r08',
      code: 'R08',
      name: 'Rectangular Penetration - Undersoaker Level (Rib)',
      description: 'Rectangular penetration using undersoaker on level rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr208.glb',
      minPitch: 0,
      maxPitch: 10,
      specifications: { soaker: 'Flat pan under ribs', foam: 'At all rib contacts', perimeter: 'Sealed all sides' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r09',
      code: 'R09',
      name: 'Rectangular Penetration - Undersoaker with Arrowhead (Rib)',
      description: 'Rectangular penetration with undersoaker and arrowhead on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr209.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { arrowhead: 'Under ribs upslope', soaker: 'Full perimeter', sequence: 'Soaker, arrowhead, roofing' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r10',
      code: 'R10',
      name: 'Rectangular Penetration - Undersoaker with Cricket (Rib)',
      description: 'Large rectangular penetration with undersoaker and cricket on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr210.glb',
      minPitch: 3,
      maxPitch: 60,
      specifications: { cricket: 'Under roofing upslope', soaker: 'Full perimeter integration', drainage: 'Positive fall both sides' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [],
    },
    {
      id: 'lrm-r11',
      code: 'R11',
      name: 'Rectangular Penetration - Hidden Gutter (Rib)',
      description: 'Rectangular penetration using hidden gutter method on rib profile roofing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-penetrations',
      modelUrl: 'https://pub-5f4c0432c70b4389a92d23c5a0047e17.r2.dev/models/gpr211.glb',
      minPitch: 3,
      maxPitch: 45,
      specifications: { gutter: 'Concealed at high side', width: '150mm minimum', overflow: 'Required' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.8', title: 'Penetration details' }],
      ventilationReqs: [{ check: 'Hidden gutter overflow provision required', required: true }],
    },
    // ============================================
    // ADDITIONAL DETAILS (without 3D models yet)
    // ============================================
    // Long-Run Metal - Ridges & Hips
    {
      id: 'lrm-ridge01',
      code: 'RIDGE01',
      name: 'Ridge Capping - Standard',
      description: 'Standard ridge capping for profiled metal roofing. Provides weather seal at roof apex.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-ridges',
      minPitch: 8,
      maxPitch: 45,
      specifications: { material: 'Matching roof profile', overlap: '150mm minimum', fixings: 'Through ridge into purlins' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.1.4', title: 'Ridge and hip details' }],
      ventilationReqs: [{ check: 'Consider ventilated ridge if roof space ventilation required', required: false }],
    },
    {
      id: 'lrm-ridge02',
      code: 'RIDGE02',
      name: 'Ridge Capping - Ventilated',
      description: 'Ventilated ridge capping allowing airflow through roof space. Essential for condensation control.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-ridges',
      minPitch: 10,
      maxPitch: 45,
      specifications: { material: 'Purpose-made ventilated ridge', freeArea: '10000mm² per linear metre minimum', mesh: 'Insect mesh required' },
      standardsRefs: [{ code: 'E3/AS1', clause: '2.1', title: 'Roof space ventilation' }],
      ventilationReqs: [{ check: 'Pair with eave ventilation for cross-flow', required: true }, { check: 'Minimum 10,000mm² free area per 100m² ceiling', required: true }],
    },
    // Long-Run Metal - Valleys
    {
      id: 'lrm-valley01',
      code: 'VALLEY01',
      name: 'Valley Gutter - Standard',
      description: 'Standard valley gutter for profiled metal roofing. Width varies based on roof pitch and catchment area.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-valleys',
      minPitch: 8,
      maxPitch: 60,
      specifications: { material: 'Galvanised steel or aluminium', thickness: '0.55mm BMT', width: '400mm minimum', upturn: '25mm each side' },
      standardsRefs: [{ code: 'E2/AS1', clause: 'Table 20', title: 'Valley gutter dimensions' }],
      ventilationReqs: [{ check: 'Valley does not obstruct cross-ventilation path', required: true }],
    },
    {
      id: 'lrm-valley02',
      code: 'VALLEY02',
      name: 'Valley Gutter - Low Pitch',
      description: 'Valley gutter for low pitch applications (under 10°). Requires wider gutter and enhanced sealing.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-valleys',
      minPitch: 3,
      maxPitch: 10,
      specifications: { material: 'Galvanised steel or aluminium', thickness: '0.55mm BMT', width: '600mm minimum', sealant: 'Butyl tape under sheeting', turnups: '40mm minimum' },
      standardsRefs: [{ code: 'E2/AS1', clause: 'Table 20', title: 'Valley gutter dimensions' }],
      ventilationReqs: [],
    },
    // Long-Run Metal - Ventilation
    {
      id: 'lrm-vent01',
      code: 'VENT01',
      name: 'Whirlybird Ventilator',
      description: 'Turbine (whirlybird) roof ventilator installation for active roof space ventilation.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-ventilation',
      minPitch: 5,
      maxPitch: 35,
      specifications: { freeArea: 'Calculate per E3/AS1', base: 'Factory or site-formed to match profile', fixings: 'Type 17 through pan' },
      standardsRefs: [{ code: 'E3/AS1', clause: '3.0.1', title: 'Roof space ventilation' }],
      ventilationReqs: [{ check: 'Position for optimal airflow (high point)', required: true }, { check: 'Balance with low-level intake vents', required: true }],
    },
    {
      id: 'lrm-vent02',
      code: 'VENT02',
      name: 'Soffit Ventilation',
      description: 'Eave soffit ventilation detail for roof space air intake.',
      substrateId: 'long-run-metal',
      categoryId: 'lrm-ventilation',
      minPitch: 3,
      maxPitch: 90,
      specifications: { freeArea: '5000mm² per 100m² ceiling minimum', mesh: '2mm insect mesh', spacing: 'Continuous or 1200mm max centres' },
      standardsRefs: [{ code: 'E3/AS1', clause: '3.0.1', title: 'Roof ventilation requirements' }],
      ventilationReqs: [{ check: 'Low-level intake for cross-ventilation', required: true }, { check: 'Clear path to roof apex ventilation', required: true }],
    },
    // Membrane details
    {
      id: 'mem-f01',
      code: 'MF01',
      name: 'Membrane Upstand to Wall',
      description: 'Standard membrane upstand termination at wall junction. Minimum height and fixing requirements.',
      substrateId: 'membrane',
      categoryId: 'mem-flashings',
      minPitch: 0,
      maxPitch: 10,
      specifications: { upturn: '150mm minimum', termination: 'Mechanical bar or adhesive', protection: 'Counter flashing required' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.2', title: 'Membrane roof requirements' }],
      ventilationReqs: [],
    },
    {
      id: 'mem-p01',
      code: 'MP01',
      name: 'Membrane Pipe Boot',
      description: 'Pipe penetration through membrane roofing. Uses welded or bonded boot detail.',
      substrateId: 'membrane',
      categoryId: 'mem-penetrations',
      minPitch: 0,
      maxPitch: 10,
      specifications: { boot: 'TPO/PVC compatible', weld: 'Hot air welded', clamp: 'Stainless steel band at top' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.2.4', title: 'Membrane penetrations' }],
      ventilationReqs: [],
    },
    // Concrete Tile details
    {
      id: 'ct-r01',
      code: 'CR01',
      name: 'Ridge Tile - Bedded',
      description: 'Mortar-bedded ridge tiles for concrete tile roofing. Traditional method with pointing.',
      substrateId: 'concrete-tile',
      categoryId: 'ct-ridges',
      minPitch: 15,
      maxPitch: 45,
      specifications: { mortar: '1:4 cement:sand', bedding: '25mm minimum', pointing: 'Weathered profile' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.3.4', title: 'Tile ridge details' }],
      ventilationReqs: [{ check: 'Consider dry ridge system for improved ventilation', required: false }],
    },
    {
      id: 'ct-r02',
      code: 'CR02',
      name: 'Ridge Tile - Dry Fix',
      description: 'Mechanically fixed ridge system for concrete tiles. Provides improved ventilation and longevity.',
      substrateId: 'concrete-tile',
      categoryId: 'ct-ridges',
      minPitch: 15,
      maxPitch: 45,
      specifications: { system: 'Proprietary dry ridge kit', fixings: 'Stainless steel screws', gasket: 'EPDM or silicone' },
      standardsRefs: [{ code: 'E2/AS1', clause: '9.3.4', title: 'Tile ridge details' }],
      ventilationReqs: [{ check: 'Dry ridge provides ventilation - pair with eave vents', required: true }],
    },
  ];
  await db.insert(details).values(detailData);
  console.log(`✅ Seeded ${detailData.length} details\n`);

  // Seed Detail Steps for key details
  console.log('📝 Seeding detail steps...');
  const stepsData = [
    // F02 - Change of Pitch Flashing steps
    { id: 'lrm-f02-s1', detailId: 'lrm-f02', stepNumber: 1, instruction: 'Ensure both roof planes are fully sheeted up to the pitch change line.', cautionNote: null },
    { id: 'lrm-f02-s2', detailId: 'lrm-f02', stepNumber: 2, instruction: 'Install building underlay with 150mm lap over the pitch change.', cautionNote: null },
    { id: 'lrm-f02-s3', detailId: 'lrm-f02', stepNumber: 3, instruction: 'Form pitch change flashing with minimum 200mm overlap onto lower pitch and 75mm upturn onto steeper pitch.', cautionNote: 'Inadequate overlap is a common failure point' },
    { id: 'lrm-f02-s4', detailId: 'lrm-f02', stepNumber: 4, instruction: 'Apply continuous butyl tape at flashing overlap onto lower roofing.', cautionNote: null },
    { id: 'lrm-f02-s5', detailId: 'lrm-f02', stepNumber: 5, instruction: 'Install upper roofing over flashing upturn. Fix through pans only.', cautionNote: 'Maintain ventilation path at pitch change' },
    // F03 - Barge Finish into Spouting steps
    { id: 'lrm-f03-s1', detailId: 'lrm-f03', stepNumber: 1, instruction: 'Verify barge board is level and securely fixed to framing.', cautionNote: null },
    { id: 'lrm-f03-s2', detailId: 'lrm-f03', stepNumber: 2, instruction: 'Install gutter/spouting to correct fall before fitting barge.', cautionNote: null },
    { id: 'lrm-f03-s3', detailId: 'lrm-f03', stepNumber: 3, instruction: 'Form barge flashing to terminate into gutter with 25mm minimum drip.', cautionNote: 'Ensure water drains into gutter, not behind' },
    { id: 'lrm-f03-s4', detailId: 'lrm-f03', stepNumber: 4, instruction: 'Apply continuous butyl sealant tape along underside where flashing contacts roof.', cautionNote: 'Sealant required in all wind zones above Low' },
    { id: 'lrm-f03-s5', detailId: 'lrm-f03', stepNumber: 5, instruction: 'Fix through pan of roofing at maximum 450mm centres using Type 17 fasteners.', cautionNote: null },
    // F06 - Hip-Ridge Finish steps
    { id: 'lrm-f06-s1', detailId: 'lrm-f06', stepNumber: 1, instruction: 'Complete hip capping installation up to apex junction point.', cautionNote: null },
    { id: 'lrm-f06-s2', detailId: 'lrm-f06', stepNumber: 2, instruction: 'Trim hip capping end to fit neatly under ridge line.', cautionNote: null },
    { id: 'lrm-f06-s3', detailId: 'lrm-f06', stepNumber: 3, instruction: 'Apply foam or butyl seal at hip-to-ridge junction.', cautionNote: 'Critical weatherproofing point' },
    { id: 'lrm-f06-s4', detailId: 'lrm-f06', stepNumber: 4, instruction: 'Install ridge capping over hip ends ensuring full coverage.', cautionNote: null },
    { id: 'lrm-f06-s5', detailId: 'lrm-f06', stepNumber: 5, instruction: 'Fix ridge at junction through pans using Type 17 fasteners.', cautionNote: null },
    // C02 - Round Penetration Overflashing steps
    { id: 'lrm-c02-s1', detailId: 'lrm-c02', stepNumber: 1, instruction: 'Mark penetration position and cut roofing sheet with 10mm clearance.', cautionNote: null },
    { id: 'lrm-c02-s2', detailId: 'lrm-c02', stepNumber: 2, instruction: 'Form metal overflashing to match corrugated profile with 150mm upslope extension.', cautionNote: null },
    { id: 'lrm-c02-s3', detailId: 'lrm-c02', stepNumber: 3, instruction: 'Apply butyl tape under overflashing at all contact points with roofing.', cautionNote: null },
    { id: 'lrm-c02-s4', detailId: 'lrm-c02', stepNumber: 4, instruction: 'Position overflashing with upslope section under upper roofing sheet.', cautionNote: 'Upper roofing must overlap flashing by minimum 150mm' },
    { id: 'lrm-c02-s5', detailId: 'lrm-c02', stepNumber: 5, instruction: 'Seal pipe-to-flashing junction with silicone or EPDM collar.', cautionNote: null },
    { id: 'lrm-c02-s6', detailId: 'lrm-c02', stepNumber: 6, instruction: 'Fix through pans only at sides and bottom of overflashing.', cautionNote: 'Never fix through upslope section' },
    // R01 - Round Penetration Through Lap steps
    { id: 'lrm-r01-s1', detailId: 'lrm-r01', stepNumber: 1, instruction: 'Position penetration through sheet lap where possible for best seal.', cautionNote: null },
    { id: 'lrm-r01-s2', detailId: 'lrm-r01', stepNumber: 2, instruction: 'Cut hole in both sheets with 10mm clearance around pipe.', cautionNote: null },
    { id: 'lrm-r01-s3', detailId: 'lrm-r01', stepNumber: 3, instruction: 'Select EPDM or silicone boot with 15% stretch fit to pipe diameter.', cautionNote: null },
    { id: 'lrm-r01-s4', detailId: 'lrm-r01', stepNumber: 4, instruction: 'Apply additional sealant at lap junction under boot base.', cautionNote: 'Extra seal required at lap' },
    { id: 'lrm-r01-s5', detailId: 'lrm-r01', stepNumber: 5, instruction: 'Position boot and fix through pans with Type 17 fasteners.', cautionNote: null },
    { id: 'lrm-r01-s6', detailId: 'lrm-r01', stepNumber: 6, instruction: 'Apply silicone fillet around entire boot perimeter.', cautionNote: null },
    // VALLEY01 - Valley Gutter steps
    { id: 'lrm-valley01-s1', detailId: 'lrm-valley01', stepNumber: 1, instruction: 'Install valley board (tilting fillet) to support valley gutter at correct angle.', cautionNote: null },
    { id: 'lrm-valley01-s2', detailId: 'lrm-valley01', stepNumber: 2, instruction: 'Lay building underlay into valley with 150mm overlap each side.', cautionNote: null },
    { id: 'lrm-valley01-s3', detailId: 'lrm-valley01', stepNumber: 3, instruction: 'Install valley gutter with 25mm minimum upturn on each side. Overlap sections minimum 150mm in direction of flow.', cautionNote: 'Check width against E2/AS1 Table 20 for your pitch' },
    { id: 'lrm-valley01-s4', detailId: 'lrm-valley01', stepNumber: 4, instruction: 'Install roofing sheets with minimum 100mm clearance from valley centreline.', cautionNote: 'Increase to 150mm for pitches below 8°' },
    { id: 'lrm-valley01-s5', detailId: 'lrm-valley01', stepNumber: 5, instruction: 'Do not fix through valley flashing - fix through roof pan only.', cautionNote: 'Critical - valley must remain watertight' },
    // RIDGE02 - Ventilated Ridge steps
    { id: 'lrm-ridge02-s1', detailId: 'lrm-ridge02', stepNumber: 1, instruction: 'Install ridge purlin to manufacturer specifications.', cautionNote: null },
    { id: 'lrm-ridge02-s2', detailId: 'lrm-ridge02', stepNumber: 2, instruction: 'Cut back roofing sheets to provide ventilation gap at apex.', cautionNote: 'Gap typically 25-40mm each side of ridge line' },
    { id: 'lrm-ridge02-s3', detailId: 'lrm-ridge02', stepNumber: 3, instruction: 'Install insect mesh over ventilation opening full length of ridge.', cautionNote: 'Required by E3/AS1' },
    { id: 'lrm-ridge02-s4', detailId: 'lrm-ridge02', stepNumber: 4, instruction: 'Position ventilated ridge cap ensuring mesh is not compressed or blocked.', cautionNote: null },
    { id: 'lrm-ridge02-s5', detailId: 'lrm-ridge02', stepNumber: 5, instruction: 'Fix ridge cap through pans at 300mm centres each side.', cautionNote: null },
    { id: 'lrm-ridge02-s6', detailId: 'lrm-ridge02', stepNumber: 6, instruction: 'Verify ventilation free area meets E3/AS1 requirements for ceiling area.', cautionNote: 'Minimum 10,000mm² per 100m² ceiling' },
  ];
  await db.insert(detailSteps).values(stepsData);
  console.log(`✅ Seeded ${stepsData.length} detail steps\n`);

  // Seed Warning Conditions
  console.log('⚠️  Seeding warning conditions...');
  const warningsData = [
    // Wind zone warnings for flashings
    { id: 'w-f01-1', detailId: 'lrm-f01', conditionType: 'wind_zone', conditionValue: 'high', warningText: 'High wind zone: Increase fixing frequency to 200mm centres', severity: 'info', nzbcRef: 'E2/AS1 9.1.7' },
    { id: 'w-f02-1', detailId: 'lrm-f02', conditionType: 'wind_zone', conditionValue: 'very-high', warningText: 'Very High wind zone: Use 150mm fixing centres and ensure all laps are sealed', severity: 'warning', nzbcRef: 'NZS 3604 7.2' },
    { id: 'w-f02-2', detailId: 'lrm-f02', conditionType: 'wind_zone', conditionValue: 'extra-high', warningText: 'Extra High wind zone: Engineering design required. This detail may need modification.', severity: 'critical', nzbcRef: 'NZS 3604 7.2' },
    { id: 'w-f03-1', detailId: 'lrm-f03', conditionType: 'wind_zone', conditionValue: 'very-high', warningText: 'Very High wind zone: Increase barge flashing fixings to 100mm centres', severity: 'warning', nzbcRef: 'E2/AS1 9.1.5' },
    { id: 'w-f04-1', detailId: 'lrm-f04', conditionType: 'wind_zone', conditionValue: 'high', warningText: 'High wind zone: Hip-to-gutter junction requires additional sealing', severity: 'warning', nzbcRef: 'E2/AS1 9.1.7.3' },
    { id: 'w-f05-1', detailId: 'lrm-f05', conditionType: 'wind_zone', conditionValue: 'very-high', warningText: 'Very High wind zone: All multi-junction flashings require butyl tape sealing', severity: 'warning', nzbcRef: 'E2/AS1 9.1.7' },
    { id: 'w-f06-1', detailId: 'lrm-f06', conditionType: 'wind_zone', conditionValue: 'high', warningText: 'High wind zone: Hip-ridge junction requires foam or butyl seal', severity: 'info', nzbcRef: 'E2/AS1 9.1.4' },
    { id: 'w-f10-1', detailId: 'lrm-f10', conditionType: 'wind_zone', conditionValue: 'high', warningText: 'High wind zone: Valley-ridge junction requires enhanced sealing', severity: 'warning', nzbcRef: 'E2/AS1' },

    // Wind zone warnings for ridges
    { id: 'w-ridge01-1', detailId: 'lrm-ridge01', conditionType: 'wind_zone', conditionValue: 'high', warningText: 'High wind zone: Use additional ridge fixings at 300mm centres', severity: 'info', nzbcRef: 'E2/AS1 9.1.4' },
    { id: 'w-ridge02-1', detailId: 'lrm-ridge02', conditionType: 'wind_zone', conditionValue: 'high', warningText: 'High wind zone: Ensure ventilated ridge is rated for wind zone', severity: 'info', nzbcRef: 'E3/AS1 2.1' },
    { id: 'w-ridge02-2', detailId: 'lrm-ridge02', conditionType: 'wind_zone', conditionValue: 'extra-high', warningText: 'Extra High wind zone: Ventilated ridge may not be suitable - consult manufacturer', severity: 'critical', nzbcRef: 'E3/AS1 2.1' },

    // Corrosion zone warnings
    { id: 'w-f01-2', detailId: 'lrm-f01', conditionType: 'corrosion_zone', conditionValue: 'c', warningText: 'Zone C (marine): Use stainless steel or hot-dip galvanised fixings', severity: 'warning', nzbcRef: 'NZS 3604 4.3' },
    { id: 'w-f07-1', detailId: 'lrm-f07', conditionType: 'corrosion_zone', conditionValue: 'c', warningText: 'Zone C (marine): Use stainless steel fixings and ensure material compatibility', severity: 'warning', nzbcRef: 'NZS 3604 4.3' },
    { id: 'w-f07-2', detailId: 'lrm-f07', conditionType: 'corrosion_zone', conditionValue: 'd', warningText: 'Zone D (severe marine): Stainless steel fixings required. Consider enhanced material specifications.', severity: 'critical', nzbcRef: 'NZS 3604 4.3' },
    { id: 'w-c02-1', detailId: 'lrm-c02', conditionType: 'corrosion_zone', conditionValue: 'd', warningText: 'Zone D (severe marine): Use silicone boot instead of EPDM for better durability', severity: 'warning', nzbcRef: 'E2/AS1 9.1.8' },
    { id: 'w-r01-1', detailId: 'lrm-r01', conditionType: 'corrosion_zone', conditionValue: 'd', warningText: 'Zone D (severe marine): EPDM boot may degrade faster - consider silicone alternative', severity: 'warning', nzbcRef: 'E2/AS1 9.1.8' },
    { id: 'w-ridge02-3', detailId: 'lrm-ridge02', conditionType: 'corrosion_zone', conditionValue: 'd', warningText: 'Zone D: Marine-grade mesh required for ventilation strips', severity: 'warning', nzbcRef: 'NZS 3604' },

    // Pitch warnings
    { id: 'w-f01-3', detailId: 'lrm-f01', conditionType: 'pitch', conditionValue: '< 5', warningText: 'Very low pitch: Additional sealing measures required at drip edge', severity: 'warning', nzbcRef: 'E2/AS1 9.1.5' },
    { id: 'w-valley01-1', detailId: 'lrm-valley01', conditionType: 'pitch', conditionValue: '< 10', warningText: 'Pitch under 10°: Valley gutter must be minimum 500mm wide', severity: 'warning', nzbcRef: 'E2/AS1 Table 20' },
    { id: 'w-valley02-1', detailId: 'lrm-valley02', conditionType: 'pitch', conditionValue: '< 8', warningText: 'Pitch under 8°: Additional sealing required. Consider upgrading to membrane system.', severity: 'critical', nzbcRef: 'E2/AS1 Table 20' },
    { id: 'w-f11-1', detailId: 'lrm-f11', conditionType: 'pitch', conditionValue: '< 8', warningText: 'Low pitch: Valley discharge onto lower roof requires butyl tape seal', severity: 'warning', nzbcRef: 'E2/AS1 Table 20' },
    { id: 'w-ridge01-2', detailId: 'lrm-ridge01', conditionType: 'pitch', conditionValue: '< 15', warningText: 'Low pitch: Use foam or rubber seal under ridge capping', severity: 'info', nzbcRef: 'E2/AS1 9.1.4' },
    { id: 'w-mem-1', detailId: 'mem-f01', conditionType: 'pitch', conditionValue: '< 3', warningText: 'Near-flat roof: Ensure positive drainage to outlets - check for ponding', severity: 'warning', nzbcRef: 'E2/AS1 9.2' },
    { id: 'w-c07-1', detailId: 'lrm-c07', conditionType: 'pitch', conditionValue: '> 45', warningText: 'Steep pitch: Cricket drainage may be compromised - ensure positive fall', severity: 'info', nzbcRef: 'E2/AS1 9.1.8' },
    { id: 'w-r07-1', detailId: 'lrm-r07', conditionType: 'pitch', conditionValue: '> 45', warningText: 'Steep pitch: Cricket drainage may be compromised - ensure positive fall', severity: 'info', nzbcRef: 'E2/AS1 9.1.8' },

    // General exposure/best practice warnings
    { id: 'w-f15-1', detailId: 'lrm-f15', conditionType: 'exposure', conditionValue: 'all', warningText: 'Large penetrations (100-300mm) require fabricated flashing with 100mm minimum upturn', severity: 'info', nzbcRef: 'E2/AS1 9.1.8' },
    { id: 'w-f16-1', detailId: 'lrm-f16', conditionType: 'exposure', conditionValue: 'all', warningText: 'Penetrations through laps require additional sealant at lap junction', severity: 'info', nzbcRef: 'E2/AS1 9.1.8' },
    { id: 'w-c11-1', detailId: 'lrm-c11', conditionType: 'exposure', conditionValue: 'all', warningText: 'Hidden gutters must have overflow provision to exterior', severity: 'warning', nzbcRef: 'E2/AS1 9.1.8' },
    { id: 'w-r11-1', detailId: 'lrm-r11', conditionType: 'exposure', conditionValue: 'all', warningText: 'Hidden gutters must have overflow provision to exterior', severity: 'warning', nzbcRef: 'E2/AS1 9.1.8' },
  ];
  await db.insert(warningConditions).values(warningsData);
  console.log(`✅ Seeded ${warningsData.length} warning conditions\n`);

  // Seed Failure Cases
  console.log('🚨 Seeding failure cases...');
  const failuresData = [
    {
      id: 'fc-1',
      caseId: 'MBIE-2023/042',
      substrateTags: ['long-run-metal'],
      detailTags: ['F07', 'flashings'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.1'],
      outcome: 'upheld',
      summary: 'Head flashing installed with only 15mm upturn instead of required 35mm minimum. Water tracked behind cladding during heavy rain events, causing damage to wall framing.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-08-15'),
    },
    {
      id: 'fc-2',
      caseId: 'LBP-2022/156',
      substrateTags: ['long-run-metal'],
      detailTags: ['F07', 'flashings'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.1', 'B2.3.1'],
      outcome: 'upheld',
      summary: 'Missing end dams on head flashings above windows. Water bypassed flashings at ends, entering wall cavity and causing moisture damage discovered during routine maintenance.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2022-11-22'),
    },
    {
      id: 'fc-3',
      caseId: 'MBIE-2023/089',
      substrateTags: ['long-run-metal'],
      detailTags: ['V01', 'valleys'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.2'],
      outcome: 'partially-upheld',
      summary: 'Valley gutter width insufficient for catchment area and pitch. Overflow during heavy rain caused water damage to ceiling. Gutter was 300mm wide on 8° pitch requiring 500mm minimum.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-06-10'),
    },
    {
      id: 'fc-4',
      caseId: 'LBP-2023/023',
      substrateTags: ['membrane'],
      detailTags: ['MP01', 'penetrations'],
      failureType: 'workmanship',
      nzbcClauses: ['E2.3.1'],
      outcome: 'upheld',
      summary: 'Membrane penetration boot not welded correctly. Cold weld allowed water ingress around pipe, causing damage to structure below flat roof.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-02-28'),
    },
    {
      id: 'fc-5',
      caseId: 'MBIE-2022/201',
      substrateTags: ['long-run-metal'],
      detailTags: ['F02', 'flashings'],
      failureType: 'structural',
      nzbcClauses: ['B1.3.1', 'E2.3.1'],
      outcome: 'upheld',
      summary: 'Incorrect fixings used in Extra High wind zone. Flashings lifted during storm event, allowing water entry and subsequent damage. Standard fixings used instead of specified stainless steel.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2022-09-14'),
    },
    {
      id: 'fc-6',
      caseId: 'LBP-2024/011',
      substrateTags: ['long-run-metal'],
      detailTags: ['R01', 'ridges'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.1'],
      outcome: 'upheld',
      summary: 'Ridge capping laps facing into prevailing weather. Wind-driven rain entered at unsealed laps, causing water staining and mould growth in ceiling space.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2024-01-18'),
    },
    {
      id: 'fc-7',
      caseId: 'MBIE-2024/033',
      substrateTags: ['long-run-metal'],
      detailTags: ['F04', 'flashings'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.1', 'E2.3.2'],
      outcome: 'upheld',
      summary: 'Apron flashing upturn only 40mm instead of required 75mm minimum. Capillary action drew water behind wall cladding during wind-driven rain, causing rot in bottom plate.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2024-03-22'),
    },
    {
      id: 'fc-8',
      caseId: 'LBP-2023/098',
      substrateTags: ['long-run-metal'],
      detailTags: ['P01', 'penetrations'],
      failureType: 'durability',
      nzbcClauses: ['B2.3.1', 'E2.3.1'],
      outcome: 'partially-upheld',
      summary: 'EPDM pipe boot failed after 8 years in Zone D marine environment. UV degradation and salt exposure caused cracking, allowing water ingress around flue pipe.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-09-05'),
    },
    {
      id: 'fc-9',
      caseId: 'MBIE-2023/156',
      substrateTags: ['concrete-tile'],
      detailTags: ['CR01', 'ridges'],
      failureType: 'workmanship',
      nzbcClauses: ['E2.3.1'],
      outcome: 'dismissed',
      summary: 'Mortar bedded ridge tiles showed minor cracking after 5 years. Investigation found cracking was within acceptable tolerance for mortar-bedded systems and not causing water ingress.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-11-14'),
    },
    {
      id: 'fc-10',
      caseId: 'LBP-2024/045',
      substrateTags: ['long-run-metal'],
      detailTags: ['F05', 'flashings'],
      failureType: 'design-error',
      nzbcClauses: ['E2.3.1', 'E2.3.2'],
      outcome: 'upheld',
      summary: 'Step flashings installed as continuous strip rather than individual stepped pieces. Water bypassed flashing at each course change, causing extensive wall damage over 3 year period.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2024-04-10'),
    },
    {
      id: 'fc-11',
      caseId: 'MBIE-2022/178',
      substrateTags: ['membrane'],
      detailTags: ['MF01', 'flashings'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.1'],
      outcome: 'upheld',
      summary: 'Membrane upstand terminated at only 75mm instead of 150mm minimum. Water entered at termination during heavy rain events, damaging interior finishes below.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2022-12-01'),
    },
    {
      id: 'fc-12',
      caseId: 'LBP-2023/167',
      substrateTags: ['long-run-metal'],
      detailTags: ['F08', 'flashings'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.1', 'E2.3.2'],
      outcome: 'partially-upheld',
      summary: 'Parapet capping joints not sealed. Water entered at joint locations, causing corrosion of parapet framing. Issue compounded by lack of parapet cavity ventilation.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-10-25'),
    },
    {
      id: 'fc-13',
      caseId: 'MBIE-2024/067',
      substrateTags: ['long-run-metal'],
      detailTags: ['V02', 'valleys'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2.3.2'],
      outcome: 'upheld',
      summary: 'Low pitch valley (6°) installed without butyl tape seal under roofing sheets. Capillary action caused persistent leaks at valley edges during light rain events.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2024-05-03'),
    },
    {
      id: 'fc-14',
      caseId: 'LBP-2024/089',
      substrateTags: ['long-run-metal'],
      detailTags: ['F10', 'box-gutter'],
      failureType: 'water-ingress',
      nzbcClauses: ['E2', 'E1'],
      outcome: 'upheld',
      summary: 'Internal box gutter installed with inadequate fall and no overflow provision. Gutter overflowed during heavy rain causing significant internal damage. Multiple Code violations found.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2024-06-12'),
    },
    {
      id: 'fc-15',
      caseId: 'MBIE-2023/201',
      substrateTags: ['long-run-metal'],
      detailTags: ['R02', 'ventilation'],
      failureType: 'durability',
      nzbcClauses: ['E3', 'B2'],
      outcome: 'upheld',
      summary: 'Unventilated roof space led to condensation damage to ceiling insulation and framing. Ridge ventilation was not installed despite being specified in building consent documents.',
      sourceUrl: 'https://www.building.govt.nz/resolving-problems/resolution-options/determinations/',
      decisionDate: new Date('2023-12-18'),
    },
  ];
  await db.insert(failureCases).values(failuresData);
  console.log(`✅ Seeded ${failuresData.length} failure cases\n`);

  // Link failures to details
  console.log('🔗 Linking failures to details...');
  const linksData = [
    { detailId: 'lrm-f07', failureCaseId: 'fc-1' },     // Ridge to Gable End - head flashing issues
    { detailId: 'lrm-f07', failureCaseId: 'fc-2' },     // Ridge to Gable End - missing end dams
    { detailId: 'lrm-valley01', failureCaseId: 'fc-3' }, // Valley gutter width issue
    { detailId: 'mem-p01', failureCaseId: 'fc-4' },     // Membrane penetration weld failure
    { detailId: 'lrm-f02', failureCaseId: 'fc-5' },     // Change of Pitch - incorrect fixings
    { detailId: 'lrm-ridge01', failureCaseId: 'fc-6' }, // Ridge capping lap direction
    { detailId: 'lrm-f04', failureCaseId: 'fc-7' },     // Hip into Spouting - upturn issue
    { detailId: 'lrm-r01', failureCaseId: 'fc-8' },     // Round penetration boot degradation
    { detailId: 'ct-r01', failureCaseId: 'fc-9' },      // Concrete tile ridge mortar cracking
    { detailId: 'lrm-f05', failureCaseId: 'fc-10' },    // Hip/Apron/Barge junction failure
    { detailId: 'mem-f01', failureCaseId: 'fc-11' },    // Membrane upstand height
    { detailId: 'lrm-f08', failureCaseId: 'fc-12' },    // Hip onto Barge - joint sealing
    { detailId: 'lrm-valley02', failureCaseId: 'fc-13' }, // Low pitch valley sealing
    { detailId: 'lrm-f10', failureCaseId: 'fc-14' },    // Valley Join & Ridge - box gutter failure
    { detailId: 'lrm-ridge02', failureCaseId: 'fc-15' }, // Ventilated ridge not installed
  ];
  await db.insert(detailFailureLinks).values(linksData);
  console.log(`✅ Seeded ${linksData.length} detail-failure links\n`);

  console.log('🎉 Database seeded successfully!\n');
  console.log('📊 Summary:');
  console.log(`   Substrates: ${substrateData.length}`);
  console.log(`   Categories: ${categoryData.length}`);
  console.log(`   Details: ${detailData.length}`);
  console.log(`   Detail Steps: ${stepsData.length}`);
  console.log(`   Warning Conditions: ${warningsData.length}`);
  console.log(`   Failure Cases: ${failuresData.length}`);
  console.log(`   Detail-Failure Links: ${linksData.length}`);
}

seed()
  .catch((error) => {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  });
